webhooks:
  - path: /webhook/test1
    method: POST
    response:
      code: 200
      headers:
        - name: Access-Control-Allow-Origin
          value: "*"
      body: "ok"
    targets:
      - http://127.0.0.1:8080/test1

  - path: /test2
    method: POST
    signature:
      headerName: X-Signature-SHA256
      alg: sha256
      prefix: sha256=
      secretFromEnv: WH_FO_TEST2_SEC
    response:
      code: 204
    targets:
      - http://127.0.0.1:8080/test2
